repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa
        name: nbqa-isort
        entry: nbqa
        language: python
        additional_dependencies: [isort]
        files: -con-soluciones\.ipynb$
        args: [isort, --profile=black]
      # - id: nbqa
      #   name: nbqa-pyupgrade
      #   entry: nbqa
      #   language: python
      #   additional_dependencies: [pyupgrade]
      #   files: \.ipynb$
      #   args: [pyupgrade, --py310-plus]
      # - id: nbqa
      #   name: nbqa-ruff
      #   entry: nbqa
      #   language: python
      #   additional_dependencies: ["ruff"]
      #   files: \.ipynb$
      #   args: ["ruff", "--select=E,F,W,N,C90", "--ignore=E501", "--exit-zero", "--fix"]
      # - id: nbqa
      #   name: nbqa-black
      #   entry: nbqa
      #   language: python
      #   additional_dependencies: [black]
      #   files: \.ipynb$
      #   args: ["black", "--line-length=100"]
